### ISSUE TITLE
There's still a weird line through Antarctica

### ISSUE THREAD

**Issue by erik-werner** [erik-werner/guldheden-projection#1]
It's easier to see it if you set CUTOFF = 5 (or whatever number you prefer that's larger than pi).

@rasmuse

**Comment by rasmuse** [comment]
Oh, yes. I don't think this is the same weird line(s) we previously to the center of the map with the previous parametrization. This weird line is in the dataset.

Geographical datasets are typically pre-cut along the antimeridian because that is convenient the commonly used world map projections which are all centered on the prime meridian. The dataset looks like this in Plate Carrée:

![Screenshot from 2020-12-14 21-56-47](https://user-images.githubusercontent.com/1210973/102135003-99e60e80-3e57-11eb-8446-9d14a140567e.png)

Therefore Antarctica as well as [Chukchi Peninsula](https://en.wikipedia.org/wiki/Chukchi_Peninsula) has an antimeridian cut. If you look closely at Chukchi you can see it  in the projection.

But Antarctica is even funnier because it also has a polar cut; the pole becomes a line. Therefore you can actually see two funny lines through Antarctica. You can clearly see all these funny things simultaneously if you
- set `CUTOFF = 5`
- set the projection rotation to `.rotate([50, -57.6887483, 0])`
- and remove the graticule:

![Screenshot from 2020-12-14 22-03-57](https://user-images.githubusercontent.com/1210973/102135640-8c7d5400-3e58-11eb-96f1-5ca318a63f3b.png)

This is the central reason for the existence of [topojson](https://github.com/topojson/topojson). Topojson can stitch together antimeridian cuts, and I thought we fixed this during our first hacking event using topojson, but clearly we did not. The dataset appears to be in topojson format, but not stitched.

Would you like to produce a correct data file, or shall I?

**Comment by rasmuse** [comment]
So we realized my answer was only partially correct. In addition to the pre-made antimeridan cuts, we also get some weird lines due to d3-geo's default clipping settings. This is seemingly resolved by setting d3-geo to circle clipping, cutting away only a tiny region around the "pole" opposite our projection centerpoint.

**Comment by erik-werner** [comment]
This seems to be exactly the remaining issue:
https://stackoverflow.com/questions/19041457/how-can-i-remove-a-line-from-the-110m-topojson-world-map

**Comment by rasmuse** [comment]
Thanks! I suggest we classify this issue as having to do with the d3-geo antimeridian vs circle clipping. Closing it as of your fix caecf16 and separating the remaining work to issue #2.
